# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt6 UI code generator 6.0.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Messenager(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Messenager):
        Messenager.setObjectName("Messenager")
        Messenager.resize(657, 508)
        self.centralwidget = QtWidgets.QWidget(Messenager)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 419, 541, 51))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 420, 71, 51))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 70, 621, 341))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(510, 30, 131, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 30, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        Messenager.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Messenager)
        self.statusbar.setObjectName("statusbar")
        Messenager.setStatusBar(self.statusbar)

        self.retranslateUi(Messenager)
        QtCore.QMetaObject.connectSlotsByName(Messenager)

    def retranslateUi(self, Messenager):
        _translate = QtCore.QCoreApplication.translate
        Messenager.setWindowTitle(_translate("Messenager", "Messenager"))
        self.label.setText(_translate("Messenager", "Messenager"))
        self.pushButton.setText(_translate("Messenager", ">"))
        self.label_2.setText(_translate("Messenager", "Ваше имя"))

app = QtWidgets.QApplication([])
window = Ui_Messenager()
window.show()
app.exec_()